tasks:
  - name: HTTP-Server
    env:
      PUBLIC_DIR: "/workspace/my-app/build"
    init: npm install http-server
    command: http-server $PUBLIC_DIR
  - name: Echo
    command: echo "Testing"
    openMode: split-right
  - name: Pipe-Multiline
    init: |
      echo "Hello"
      echo "World"
  - name: Angle-Multiline
    init: > 
      echo "Hello" &&
      echo "World"
ports:
  - port: 80
