tasks:
  - name: "Default1"
    command: echo 'Default1'
  - name: "TabBefore1"
    command: echo 'TabBefore1'
    openMode: tab-before
  - name: "TabAfter1"
    command: echo 'TabAfter1'
    openMode: tab-after
  - name: "SplitRight1"
    command: echo 'SplitRight1'
    openMode: split-right
  - name: "TabAfter2"
    command: echo 'TabAfter2'
    openMode: tab-after
  - name: "TabBefore2"
    command: echo 'TabBefore2'
    openMode: tab-before
  - name: "Default2"
    command: echo 'Default2'
  - name: "SplitLeft1"
    command: echo 'SplitLeft1'
    openMode: split-left
  - name: "SplitLeft2"
    command: echo 'SplitLeft2'
    openMode: split-left
  - name: "SplitRight2"
    command: echo 'SplitRight2'
    openMode: split-right